service: aws-crypto-price-predictions
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  # Processor architecture: 'x86_64' or 'arm64' via Graviton2 (default: x86_64)
  architecture: x86_64
  logs:
    restApi: true


package:
  exclude:
    - .git/**
    - .vscode/**
    - venv/**
    - env/**
    - README.md
    - .gitignore

functions:
  lambda_handler:
    handler: handler.lambda_handler
    events:
      - httpApi:
          path: /chat
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    noDeploy:
      - setuptools
      - boto3
      - botocore
      - s3transfer
    dockerizePip: non-linux
    slim: true